import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase = createClient('https://zlwkaxsajkopauvhwgsm.supabase.co', 'sb_publishable_9IfHjvS2rXP47gE1JAF2Ww_RxU9H20Y');
const supabase = createClient('https://zlwkaxsajkopauvhwgsm.supabase.co', 'sb_publishable_9IfHjvS2rXP47gE1JAF2Ww_RxU9H20Y', {auth:{experimental:{passkey:true}}});
const app = document.querySelector('#app');
const anchor = new Date(2026, 7, 21);
const seedBills = [
  ['Rent','A','fixed',717.5],['Internet','A','fixed',35],['Car Insurance','A','variable',null],['CareCredit','A','variable',null],['PayPal Credit Card','A','variable',null],
  ['FPL','B','variable',null],['Phone','B','variable',null],['Water','B','variable',null],['Car Payment','B','editable',null],['Navy Federal Credit Card','B','variable',null],['Capital One Credit Card','B','variable',null]
];
let state={session:null,index:0,page:'paycheck',data:null,month:null,monthly:[]};
let state={session:null,index:0,page:'paycheck',data:null,month:null,monthly:[],settings:[],editing:null};
const fmt=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const val=v=>{const x=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(x)&&x>=0?Math.round(x*100)/100:null};
const date=d=>new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'}).format(new Date(`${d}T12:00:00`));
const info=index=>{const d=new Date(anchor.getTime()+index*12096e5);return{index,date:d.toISOString().slice(0,10),group:Math.abs(index)%2?'A':'B'}};
const type=t=>t==='fixed'?'Fixed':t==='editable'?'Fixed, editable':'Variable';
const monthLabel=(y,m)=>new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(y,m,1));

async function ensureSeed(){const{count,error}=await supabase.from('bills').select('*',{count:'exact',head:true});if(error)throw error;if(!count){const{error:e}=await supabase.from('bills').insert(seedBills.map(([name,paycheck_group,amount_type,default_amount])=>({name,paycheck_group,amount_type,default_amount})));if(e)throw e}}
async function load(index=state.index){state.index=index;const p=info(index);const[{data:bills,error:bErr},{data:paychecks,error:pErr}]=await Promise.all([supabase.from('bills').select('*').eq('active',true).eq('paycheck_group',p.group).order('created_at'),supabase.from('paychecks').select('*').eq('paycheck_date',p.date).maybeSingle()]);if(bErr||pErr)throw bErr||pErr;let paycheck=paychecks;if(!paycheck){const r=await supabase.from('paychecks').insert({paycheck_date:p.date,paycheck_group:p.group}).select().single();if(r.error)throw r.error;paycheck=r.data}const{data:entries,error:eErr}=await supabase.from('bill_entries').select('*').eq('paycheck_id',paycheck.id);if(eErr)throw eErr;const map=Object.fromEntries(entries.map(e=>[e.bill_id,e]));const missing=bills.filter(b=>!map[b.id]).map(b=>({paycheck_id:paycheck.id,bill_id:b.id,amount:b.amount_type==='variable'?null:b.default_amount}));if(missing.length){const r=await supabase.from('bill_entries').insert(missing).select();if(r.error)throw r.error;r.data.forEach(e=>map[e.bill_id]=e)}state.data={p,bills,paycheck,entries:map};render()}
async function saveEntry(billId,amount,paid){const e=state.data.entries[billId];e.amount=amount;e.paid=paid;e.paid_at=paid?(e.paid_at||new Date().toISOString()):null;render();const{error}=await supabase.from('bill_entries').update({amount,paid,paid_at:e.paid_at,updated_at:new Date().toISOString()}).eq('id',e.id);if(error){alert('Could not save that change.');await load()}}
async function saveIncome(amount){state.data.paycheck.amount=amount;render();const{error}=await supabase.from('paychecks').update({amount}).eq('id',state.data.paycheck.id);if(error){alert('Could not save that change.');await load()}}
function header(){return`<header class="topbar"><div class="brand">Paycheck Planner<span class="subbrand">Private, simple bill planning</span></div><button class="text-btn" data-action="signout">Sign out</button></header><nav class="tabs"><button data-action="paycheck-view" class="${state.page==='paycheck'?'active':''}">Paychecks</button><button data-action="monthly-view" class="${state.page==='monthly'?'active':''}">Monthly</button></nav>`}
function header(){return`<header class="topbar"><div class="brand">Paycheck Planner<span class="subbrand">Private, simple bill planning</span></div><div><button class="text-btn" data-action="register-passkey">Set up Face ID</button><button class="text-btn" data-action="settings">Edit bills</button><button class="text-btn" data-action="signout">Sign out</button></div></header><nav class="tabs"><button data-action="paycheck-view" class="${state.page==='paycheck'?'active':''}">Paychecks</button><button data-action="monthly-view" class="${state.page==='monthly'?'active':''}">Monthly</button></nav>`}
function render(){if(state.page==='monthly')return renderMonth();const{p,bills,paycheck,entries}=state.data,total=bills.reduce((n,b)=>n+(entries[b.id].amount||0),0),paid=bills.filter(b=>entries[b.id].paid).length,remain=paycheck.amount==null?null:paycheck.amount-total;app.innerHTML=`${header()}<section class="paycheck-hero"><p class="eyebrow">Your paycheck</p><div class="hero-row"><div><h1>Paycheck ${p.group}</h1><p class="date">${date(p.date)}</p></div></div></section><nav class="navigation"><button class="icon-btn" data-action="prev">‹</button><span class="date-nav">${state.index===0?'Current paycheck':state.index<0?`${-state.index} paycheck${state.index===-1?'':'s'} ago`:`${state.index} ahead`}</span><button class="icon-btn" data-action="next">›</button></nav><section class="card amount-card"><span class="label">Paycheck amount</span><label class="currency-input">$<input data-income inputmode="decimal" placeholder="0.00" value="${paycheck.amount??''}"></label></section><div class="section-title"><h2>Bills</h2><span class="progress">${paid} of ${bills.length} paid</span></div><section class="card bills-card">${bills.map(b=>`<article class="bill"><button class="check ${entries[b.id].paid?'paid':''}" data-paid="${b.id}">${entries[b.id].paid?'✓':''}</button><div><div class="bill-name">${b.name}</div><div class="bill-meta ${entries[b.id].amount==null?'attention':''}">${entries[b.id].amount==null?'Amount needed':type(b.amount_type)}</div></div><label class="currency-input">$<input data-entry="${b.id}" inputmode="decimal" placeholder="—" value="${entries[b.id].amount??''}"></label></article>`).join('')}</section><section class="card summary"><div class="summary-row"><span>Total bills</span><strong>${fmt(total)}</strong></div><div class="summary-row remaining"><span>Remaining</span><strong>${fmt(remain)}</strong></div></section>`}
async function loadMonth(y,m){state.page='monthly';state.month={y,m};const periods=[];for(let i=Math.floor((new Date(y,m,1)-anchor)/12096e5)-1;i<Math.floor((new Date(y,m+1,1)-anchor)/12096e5)+2;i++){const p=info(i),d=new Date(`${p.date}T12:00:00`);if(d.getMonth()!==m)continue;await load(i);periods.push(state.data)}state.monthly=periods;renderMonth()}
function renderMonth(){const{y,m}=state.month;const total=state.monthly.reduce((n,d)=>n+d.bills.reduce((x,b)=>x+(d.entries[b.id].amount||0),0),0);app.innerHTML=`${header()}<div class="month-head"><button class="icon-btn" data-month="-1">‹</button><h1>${monthLabel(y,m)}</h1><button class="icon-btn" data-month="1">›</button></div><div class="section-title"><h2>Month at a glance</h2><span class="progress">${fmt(total)} in bills</span></div>${state.monthly.map(d=>{const total=d.bills.reduce((n,b)=>n+(d.entries[b.id].amount||0),0),paid=d.bills.filter(b=>d.entries[b.id].paid).length,rem=d.paycheck.amount==null?null:d.paycheck.amount-total;return`<article class="card monthly-card"><div class="period-top"><div><h2>Paycheck ${d.p.group}</h2><span>${date(d.p.date)}</span></div><span>${paid} of ${d.bills.length} paid</span></div><div class="period-stats"><div><small>Total bills</small><strong>${fmt(total)}</strong></div><div><small>Remaining</small><strong>${fmt(rem)}</strong></div></div><button class="text-btn" data-open="${d.p.index}">Open paycheck →</button></article>`}).join('')}`}
async function loadSettings(){state.page='settings';state.editing=null;const{data,error}=await supabase.from('bills').select('*').eq('active',true).order('paycheck_group').order('created_at');if(error)throw error;state.settings=data;renderSettings()}
function renderSettings(){const bill=state.editing&&state.settings.find(b=>b.id===state.editing);app.innerHTML=`${header()}<section class="paycheck-hero"><p class="eyebrow">Bill management</p><h1>Recurring bills</h1><p class="date">Set the amount that should prefill on future paychecks.</p></section><section class="card settings-list">${state.settings.map(b=>`<button class="settings-item" data-edit="${b.id}"><div><div class="bill-name">${b.name}</div><div class="bill-meta">Paycheck ${b.paycheck_group} · ${type(b.amount_type)}${b.default_amount==null?'':' · '+fmt(b.default_amount)}</div></div><span class="chevron">›</span></button>`).join('')}</section>${bill?`<div class="modal-backdrop"><section class="sheet"><div class="handle"></div><div class="sheet-head"><h2>Edit ${bill.name}</h2><button class="icon-btn" type="button" data-close-editor>×</button></div><form id="bill-form"><input type="hidden" name="id" value="${bill.id}"><div class="form-group"><label>Bill name</label><input class="field" name="name" value="${bill.name}" required></div><div class="form-grid"><div class="form-group"><label>Paycheck</label><select class="field" name="group"><option value="A" ${bill.paycheck_group==='A'?'selected':''}>Paycheck A</option><option value="B" ${bill.paycheck_group==='B'?'selected':''}>Paycheck B</option></select></div><div class="form-group"><label>Amount type</label><select class="field" name="amount_type"><option value="variable" ${bill.amount_type==='variable'?'selected':''}>Variable</option><option value="fixed" ${bill.amount_type==='fixed'?'selected':''}>Fixed</option><option value="editable" ${bill.amount_type==='editable'?'selected':''}>Fixed, editable</option></select></div></div><div class="form-group"><label>Recurring amount</label><label class="field currency-input">$<input name="default_amount" inputmode="decimal" placeholder="Leave blank for variable" value="${bill.default_amount??''}"></label></div><p class="auth-note">This prefills future paychecks. Amounts already entered for past or current paychecks stay independent.</p><div class="actions"><button type="button" class="secondary" data-close-editor>Cancel</button><button class="primary" type="submit">Save bill</button></div></form></section></div>`:''}`}
function auth(){app.innerHTML=`<section class="auth"><p class="eyebrow">Welcome</p><h1>Paycheck Planner</h1><p>Sign in to your private planner.</p><form id="auth-form" novalidate><input class="field" type="email" name="email" placeholder="Email" autocomplete="email" required><input class="field" type="password" name="password" placeholder="Password" autocomplete="current-password" required><button class="primary" type="submit">Continue</button><p id="auth-status" class="auth-note" role="status" aria-live="polite"></p></form><p class="auth-note">New here? Your first submission creates your account.</p></section>`}
app.addEventListener('click',async e=>{const t=e.target.closest('[data-action],[data-paid],[data-open],[data-month]');if(!t)return;if(t.dataset.paid){const x=state.data.entries[t.dataset.paid];return saveEntry(t.dataset.paid,x.amount,!x.paid)}if(t.dataset.action==='prev')return load(state.index-1);if(t.dataset.action==='next')return load(state.index+1);if(t.dataset.action==='signout'){await supabase.auth.signOut();return auth()}if(t.dataset.action==='monthly-view'){const d=new Date(`${state.data.p.date}T12:00:00`);return loadMonth(d.getFullYear(),d.getMonth())}if(t.dataset.action==='paycheck-view'){state.page='paycheck';return load(state.index)}if(t.dataset.open){state.page='paycheck';return load(Number(t.dataset.open))}if(t.dataset.month){const d=new Date(state.month.y,state.month.m+Number(t.dataset.month),1);return loadMonth(d.getFullYear(),d.getMonth())}});
function auth(){app.innerHTML=`<section class="auth"><p class="eyebrow">Welcome</p><h1>Paycheck Planner</h1><p>Sign in to your private planner.</p><form id="auth-form" novalidate><input class="field" type="email" name="email" placeholder="Email" autocomplete="email" required><input class="field" type="password" name="password" placeholder="Password" autocomplete="current-password" required><button class="primary" type="submit">Continue</button><p id="auth-status" class="auth-note" role="status" aria-live="polite"></p></form><div class="auth-divider">or</div><button class="secondary passkey-btn" type="button" data-action="passkey-login">Continue with Face ID</button><p class="auth-note">Set up Face ID after your first regular sign-in. New here? Your first submission creates your account.</p></section>`}
app.addEventListener('click',async e=>{const t=e.target.closest('[data-action],[data-paid],[data-open],[data-month],[data-edit],[data-close-editor]');if(!t)return;if(t.dataset.edit){state.editing=t.dataset.edit;return renderSettings()}if(t.dataset.closeEditor!==undefined){state.editing=null;return renderSettings()}if(t.dataset.paid){const x=state.data.entries[t.dataset.paid];return saveEntry(t.dataset.paid,x.amount,!x.paid)}if(t.dataset.action==='prev')return load(state.index-1);if(t.dataset.action==='next')return load(state.index+1);if(t.dataset.action==='settings')return loadSettings();if(t.dataset.action==='register-passkey'){t.disabled=true;try{const{error}=await supabase.auth.registerPasskey();if(error)throw error;alert('Face ID is set up for Paycheck Planner.')}catch(error){alert(error.message||'Face ID setup did not finish. Please try again.')}finally{t.disabled=false}return}if(t.dataset.action==='passkey-login'){const status=document.querySelector('#auth-status');t.disabled=true;if(status)status.textContent='Opening Face ID…';try{const{data,error}=await supabase.auth.signInWithPasskey();if(error)throw error;state.session=data.session;await ensureSeed();await load()}catch(error){if(status)status.textContent=error.message||'Face ID sign-in did not finish. You can still sign in with email.'}finally{t.disabled=false}return}if(t.dataset.action==='signout'){await supabase.auth.signOut();return auth()}if(t.dataset.action==='monthly-view'){const d=new Date(`${state.data.p.date}T12:00:00`);return loadMonth(d.getFullYear(),d.getMonth())}if(t.dataset.action==='paycheck-view'){state.page='paycheck';return load(state.index)}if(t.dataset.open){state.page='paycheck';return load(Number(t.dataset.open))}if(t.dataset.month){const d=new Date(state.month.y,state.month.m+Number(t.dataset.month),1);return loadMonth(d.getFullYear(),d.getMonth())}});
app.addEventListener('change',e=>{if(e.target.dataset.income!==undefined)saveIncome(val(e.target.value));if(e.target.dataset.entry){const x=state.data.entries[e.target.dataset.entry];saveEntry(e.target.dataset.entry,val(e.target.value),x.paid)}});
app.addEventListener('submit',async e=>{if(e.target.id!=='bill-form')return;e.preventDefault();const form=new FormData(e.target),id=String(form.get('id')),amountType=String(form.get('amount_type')),payload={name:String(form.get('name')).trim(),paycheck_group:String(form.get('group')),amount_type:amountType,default_amount:amountType==='variable'?null:val(form.get('default_amount'))};const{error}=await supabase.from('bills').update(payload).eq('id',id);if(error)return alert(`Could not save this bill: ${error.message}`);await loadSettings()});
app.addEventListener('submit',async e=>{if(e.target.id!=='auth-form')return;e.preventDefault();const f=new FormData(e.target),email=String(f.get('email')||'').trim(),password=String(f.get('password')||''),button=e.target.querySelector('button[type="submit"]'),status=e.target.querySelector('#auth-status'),say=message=>{status.textContent=message};if(!/^\S+@\S+\.\S+$/.test(email))return say('Please enter a valid email address.');if(password.length<6)return say('Your password must be at least 6 characters.');button.disabled=true;say('Signing you in…');try{let r=await supabase.auth.signInWithPassword({email,password});if(r.error&&/Invalid login/i.test(r.error.message))r=await supabase.auth.signUp({email,password});if(r.error)throw r.error;if(!r.data.session){say('Check your email to confirm your account, then return here and sign in.');return}state.session=r.data.session;await ensureSeed();await load()}catch(error){console.error(error);const detail=[error?.message,error?.details,error?.hint,error?.code,error?.name,error?.status].filter(Boolean).join(' · ');say(detail?`Could not open your planner: ${detail}`:'Your account may be signed in, but the planner database could not be reached.')}finally{if(document.contains(button))button.disabled=false}});
supabase.auth.getSession().then(async({data:{session}})=>{if(!session)return auth();state.session=session;try{await ensureSeed();await load()}catch(e){console.error(e);app.innerHTML='<p class="empty-note">Setup error. Run the Supabase schema first.</p>'}});
