import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase = createClient('https://zlwkaxsajkopauvhwgsm.supabase.co', 'sb_publishable_9IfHjvS2rXP47gE1JAF2Ww_RxU9H20Y');
const app = document.querySelector('#app');
const anchor = new Date(2026, 7, 21);
const seedBills = [
  ['Rent','A','fixed',717.5],['Internet','A','fixed',35],['Car Insurance','A','variable',null],['CareCredit','A','variable',null],['PayPal Credit Card','A','variable',null],
  ['FPL','B','variable',null],['Phone','B','variable',null],['Water','B','variable',null],['Car Payment','B','editable',null],['Navy Federal Credit Card','B','variable',null],['Capital One Credit Card','B','variable',null]
];
let state={session:null,index:0,page:'paycheck',data:null,month:null,monthly:[]};
const fmt=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const val=v=>{const x=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(x)&&x>=0?Math.round(x*100)/100:null};
const date=d=>new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'}).format(new Date(`${d}T12:00:00`));
const info=index=>{const d=new Date(anchor.getTime()+index*12096e5);return{index,date:d.toISOString().slice(0,10),group:Math.abs(index)%2?'A':'B'}};
const type=t=>t==='fixed'?'Fixed':t==='editable'?'Fixed, editable':'Variable';
const monthLabel=(y,m)=>new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(y,m,1));

async function ensureSeed(){const{count,error}=await supabase.from('bills').select('*',{count:'exact',head:true});if(error)throw error;if(!count){const{error:e}=await supabase.from('bills').insert(seedBills.map(([name,paycheck_group,amount_type,default_amount])=>({name,paycheck_group,amount_type,default_amount})));if(e)throw e}}
async function load(index=state.index){state.index=index;const p=info(index);const[{data:bills,error:bErr},{data:paychecks,error:pErr}]=await Promise.all([supabase.from('bills').select('*').eq('active',true).eq('paycheck_group',p.group).order('created_at'),supabase.from('paychecks').select('*').eq('paycheck_date',p.date).maybeSingle()]);if(bErr||pErr)throw bErr||pErr;let paycheck=paychecks;if(!paycheck){const r=await supabase.from('paychecks').insert({paycheck_date:p.date,paycheck_group:p.group}).select().single();if(r.error)throw r.error;paycheck=r.data}const{data:entries,error:eErr}=await supabase.from('bill_entries').select('*').eq('paycheck_id',paycheck.id);if(eErr)throw eErr;const map=Object.fromEntries(entries.map(e=>[e.bill_id,e]));const missing=bills.filter(b=>!map[b.id]).map(b=>({paycheck_id:paycheck.id,bill_id:b.id,amount:b.amount_type==='variable'?null:b.default_amount}));if(missing.length){const r=await supabase.from('bill_entries').insert(missing).select();if(r.error)throw r.error;r.data.forEach(e=>map[e.bill_id]=e)}state.data={p,bills,paycheck,entries:map};render()}
async function saveEntry(billId,amount,paid){const e=state.data.entries[billId];e.amount=amount;e.paid=paid;e.paid_at=paid?(e.paid_at||new Date().toISOString()):null;render();const{error}=await supabase.from('bill_entries').update({amount,paid,paid_at:e.paid_at,updated_at:new Date().toISOString()}).eq('id',e.id);if(error){alert('Could not save that change.');await load()}}
async function saveIncome(amount){state.data.paycheck.amount=amount;render();const{error}=await supabase.from('paychecks').update({amount}).eq('id',state.data.paycheck.id);if(error){alert('Could not save that change.');await load()}}
function header(){return`<header class="topbar"><div class="brand">Paycheck Planner<span class="subbrand">Private, simple bill planning</span></div><button class="text-btn" data-action="signout">Sign out</button></header><nav class="tabs"><button data-action="paycheck-view" class="${state.page==='paycheck'?'active':''}">Paychecks</button><button data-action="monthly-view" class="${state.page==='monthly'?'active':''}">Monthly</button></nav>`}
function render(){if(state.page==='monthly')return renderMonth();const{p,bills,paycheck,entries}=state.data,total=bills.reduce((n,b)=>n+(entries[b.id].amount||0),0),paid=bills.filter(b=>entries[b.id].paid).length,remain=paycheck.amount==null?null:paycheck.amount-total;app.innerHTML=`${header()}<section class="paycheck-hero"><p class="eyebrow">Your paycheck</p><div class="hero-row"><div><h1>Paycheck ${p.group}</h1><p class="date">${date(p.date)}</p></div></div></section><nav class="navigation"><button class="icon-btn" data-action="prev">‹</button><span class="date-nav">${state.index===0?'Current paycheck':state.index<0?`${-state.index} paycheck${state.index===-1?'':'s'} ago`:`${state.index} ahead`}</span><button class="icon-btn" data-action="next">›</button></nav><section class="card amount-card"><span class="label">Paycheck amount</span><label class="currency-input">$<input data-income inputmode="decimal" placeholder="0.00" value="${paycheck.amount??''}"></label></section><div class="section-title"><h2>Bills</h2><span class="progress">${paid} of ${bills.length} paid</span></div><section class="card bills-card">${bills.map(b=>`<article class="bill"><button class="check ${entries[b.id].paid?'paid':''}" data-paid="${b.id}">${entries[b.id].paid?'✓':''}</button><div><div class="bill-name">${b.name}</div><div class="bill-meta ${entries[b.id].amount==null?'attention':''}">${entries[b.id].amount==null?'Amount needed':type(b.amount_type)}</div></div><label class="currency-input">$<input data-entry="${b.id}" inputmode="decimal" placeholder="—" value="${entries[b.id].amount??''}"></label></article>`).join('')}</section><section class="card summary"><div class="summary-row"><span>Total bills</span><strong>${fmt(total)}</strong></div><div class="summary-row remaining"><span>Remaining</span><strong>${fmt(remain)}</strong></div></section>`}
async function loadMonth(y,m){state.page='monthly';state.month={y,m};const periods=[];for(let i=Math.floor((new Date(y,m,1)-anchor)/12096e5)-1;i<Math.floor((new Date(y,m+1,1)-anchor)/12096e5)+2;i++){const p=info(i),d=new Date(`${p.date}T12:00:00`);if(d.getMonth()!==m)continue;await load(i);periods.push(state.data)}state.monthly=periods;renderMonth()}
function renderMonth(){const{y,m}=state.month;const total=state.monthly.reduce((n,d)=>n+d.bills.reduce((x,b)=>x+(d.entries[b.id].amount||0),0),0);app.innerHTML=`${header()}<div class="month-head"><button class="icon-btn" data-month="-1">‹</button><h1>${monthLabel(y,m)}</h1><button class="icon-btn" data-month="1">›</button></div><div class="section-title"><h2>Month at a glance</h2><span class="progress">${fmt(total)} in bills</span></div>${state.monthly.map(d=>{const total=d.bills.reduce((n,b)=>n+(d.entries[b.id].amount||0),0),paid=d.bills.filter(b=>d.entries[b.id].paid).length,rem=d.paycheck.amount==null?null:d.paycheck.amount-total;return`<article class="card monthly-card"><div class="period-top"><div><h2>Paycheck ${d.p.group}</h2><span>${date(d.p.date)}</span></div><span>${paid} of ${d.bills.length} paid</span></div><div class="period-stats"><div><small>Total bills</small><strong>${fmt(total)}</strong></div><div><small>Remaining</small><strong>${fmt(rem)}</strong></div></div><button class="text-btn" data-open="${d.p.index}">Open paycheck →</button></article>`}).join('')}`}
function auth(){app.innerHTML=`<section class="auth"><p class="eyebrow">Welcome</p><h1>Paycheck Planner</h1><p>Sign in to your private planner.</p><form id="auth-form"><input class="field" type="email" name="email" placeholder="Email" required><input class="field" type="password" name="password" placeholder="Password" minlength="6" required><button class="primary" type="submit">Continue</button></form><p class="auth-note">New here? Your first submission creates your account.</p></section>`}
app.addEventListener('click',async e=>{const t=e.target.closest('[data-action],[data-paid],[data-open],[data-month]');if(!t)return;if(t.dataset.paid){const x=state.data.entries[t.dataset.paid];return saveEntry(t.dataset.paid,x.amount,!x.paid)}if(t.dataset.action==='prev')return load(state.index-1);if(t.dataset.action==='next')return load(state.index+1);if(t.dataset.action==='signout'){await supabase.auth.signOut();return auth()}if(t.dataset.action==='monthly-view'){const d=new Date(`${state.data.p.date}T12:00:00`);return loadMonth(d.getFullYear(),d.getMonth())}if(t.dataset.action==='paycheck-view'){state.page='paycheck';return load(state.index)}if(t.dataset.open){state.page='paycheck';return load(Number(t.dataset.open))}if(t.dataset.month){const d=new Date(state.month.y,state.month.m+Number(t.dataset.month),1);return loadMonth(d.getFullYear(),d.getMonth())}});
app.addEventListener('change',e=>{if(e.target.dataset.income!==undefined)saveIncome(val(e.target.value));if(e.target.dataset.entry){const x=state.data.entries[e.target.dataset.entry];saveEntry(e.target.dataset.entry,val(e.target.value),x.paid)}});
app.addEventListener('submit',async e=>{if(e.target.id!=='auth-form')return;e.preventDefault();const f=new FormData(e.target),email=f.get('email'),password=f.get('password');let r=await supabase.auth.signInWithPassword({email,password});if(r.error&&/Invalid login/i.test(r.error.message))r=await supabase.auth.signUp({email,password});if(r.error)return alert(r.error.message);if(!r.data.session)return alert('Check your email to confirm your account, then sign in.');state.session=r.data.session;await ensureSeed();load()});
supabase.auth.getSession().then(async({data:{session}})=>{if(!session)return auth();state.session=session;try{await ensureSeed();await load()}catch(e){console.error(e);app.innerHTML='<p class="empty-note">Setup error. Run the Supabase schema first.</p>'}});
